allowBuilds:
  "@sentry/cli": true
  better-sqlite3: true
  esbuild: true
  sharp: true
  workerd: true
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: ^0.1.22
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
autoInstallPeers: true
enablePrePostScripts: true
minimumReleaseAge: 0
