// Generated by Wrangler on Sun Jun 09 2024 20:10:19 GMT+0530 (India Standard Time)
// by running `wrangler types --env-interface CloudflareEnv src/cloudflare.d.ts`

interface CloudflareEnv {
	D1_DB: D1Database;
}
