/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as pureRouteRouteImport } from './routes/(pure)/route'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as pureResumeRouteImport } from './routes/(pure)/resume'
import { Route as pureFancyPantsRouteImport } from './routes/(pure)/fancy-pants'
import { Route as mainRwcRouteImport } from './routes/(main)/rwc'
import { Route as mainKeebsRouteImport } from './routes/(main)/keebs'
import { Route as mainKarmaRouteImport } from './routes/(main)/karma'
import { Route as mainAboutRouteImport } from './routes/(main)/about'
import { Route as mainSlugRouteImport } from './routes/(main)/$slug'
import { Route as mainNewsletterIndexRouteImport } from './routes/(main)/newsletter/index'
import { Route as mainBlogIndexRouteImport } from './routes/(main)/blog/index'
import { Route as mainAocIndexRouteImport } from './routes/(main)/aoc/index'
import { Route as mainNewsletterSlugRouteImport } from './routes/(main)/newsletter/$slug'
import { Route as mainBlogSlugRouteImport } from './routes/(main)/blog/$slug'
import { Route as apiApiPresenceRouteImport } from './routes/(api)/api/presence'
import { Route as apiApiCoffeeRouteImport } from './routes/(api)/api/coffee'
import { Route as mainfoobarFoobarIndexRouteImport } from './routes/(main)/(foobar)/foobar/index'
import { Route as mainAocYearDayRouteImport } from './routes/(main)/aoc/$year/$day'
import { Route as mainfoobarFoobarSlugRouteImport } from './routes/(main)/(foobar)/foobar/$slug'
import { Route as apiPrxyPlsblJsScriptRouteImport } from './routes/(api)/prxy/plsbl/js/$script'
import { Route as apiPrxyPlsblApiEventRouteImport } from './routes/(api)/prxy/plsbl/api/event'

const pureRouteRoute = pureRouteRouteImport.update({
  id: '/(pure)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const pureResumeRoute = pureResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => pureRouteRoute,
} as any)
const pureFancyPantsRoute = pureFancyPantsRouteImport.update({
  id: '/fancy-pants',
  path: '/fancy-pants',
  getParentRoute: () => pureRouteRoute,
} as any)
const mainRwcRoute = mainRwcRouteImport.update({
  id: '/rwc',
  path: '/rwc',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainKeebsRoute = mainKeebsRouteImport.update({
  id: '/keebs',
  path: '/keebs',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainKarmaRoute = mainKarmaRouteImport.update({
  id: '/karma',
  path: '/karma',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAboutRoute = mainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainSlugRoute = mainSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainNewsletterIndexRoute = mainNewsletterIndexRouteImport.update({
  id: '/newsletter/',
  path: '/newsletter/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainBlogIndexRoute = mainBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAocIndexRoute = mainAocIndexRouteImport.update({
  id: '/aoc/',
  path: '/aoc/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainNewsletterSlugRoute = mainNewsletterSlugRouteImport.update({
  id: '/newsletter/$slug',
  path: '/newsletter/$slug',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainBlogSlugRoute = mainBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => mainRouteRoute,
} as any)
const apiApiPresenceRoute = apiApiPresenceRouteImport.update({
  id: '/(api)/api/presence',
  path: '/api/presence',
  getParentRoute: () => rootRouteImport,
} as any)
const apiApiCoffeeRoute = apiApiCoffeeRouteImport.update({
  id: '/(api)/api/coffee',
  path: '/api/coffee',
  getParentRoute: () => rootRouteImport,
} as any)
const mainfoobarFoobarIndexRoute = mainfoobarFoobarIndexRouteImport.update({
  id: '/(foobar)/foobar/',
  path: '/foobar/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAocYearDayRoute = mainAocYearDayRouteImport.update({
  id: '/aoc/$year/$day',
  path: '/aoc/$year/$day',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainfoobarFoobarSlugRoute = mainfoobarFoobarSlugRouteImport.update({
  id: '/(foobar)/foobar/$slug',
  path: '/foobar/$slug',
  getParentRoute: () => mainRouteRoute,
} as any)
const apiPrxyPlsblJsScriptRoute = apiPrxyPlsblJsScriptRouteImport.update({
  id: '/(api)/prxy/plsbl/js/$script',
  path: '/prxy/plsbl/js/$script',
  getParentRoute: () => rootRouteImport,
} as any)
const apiPrxyPlsblApiEventRoute = apiPrxyPlsblApiEventRouteImport.update({
  id: '/(api)/prxy/plsbl/api/event',
  path: '/prxy/plsbl/api/event',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$slug': typeof mainSlugRoute
  '/about': typeof mainAboutRoute
  '/karma': typeof mainKarmaRoute
  '/keebs': typeof mainKeebsRoute
  '/rwc': typeof mainRwcRoute
  '/fancy-pants': typeof pureFancyPantsRoute
  '/resume': typeof pureResumeRoute
  '/': typeof mainIndexRoute
  '/api/coffee': typeof apiApiCoffeeRoute
  '/api/presence': typeof apiApiPresenceRoute
  '/blog/$slug': typeof mainBlogSlugRoute
  '/newsletter/$slug': typeof mainNewsletterSlugRoute
  '/aoc/': typeof mainAocIndexRoute
  '/blog/': typeof mainBlogIndexRoute
  '/newsletter/': typeof mainNewsletterIndexRoute
  '/foobar/$slug': typeof mainfoobarFoobarSlugRoute
  '/aoc/$year/$day': typeof mainAocYearDayRoute
  '/foobar/': typeof mainfoobarFoobarIndexRoute
  '/prxy/plsbl/api/event': typeof apiPrxyPlsblApiEventRoute
  '/prxy/plsbl/js/$script': typeof apiPrxyPlsblJsScriptRoute
}
export interface FileRoutesByTo {
  '/$slug': typeof mainSlugRoute
  '/about': typeof mainAboutRoute
  '/karma': typeof mainKarmaRoute
  '/keebs': typeof mainKeebsRoute
  '/rwc': typeof mainRwcRoute
  '/fancy-pants': typeof pureFancyPantsRoute
  '/resume': typeof pureResumeRoute
  '/': typeof mainIndexRoute
  '/api/coffee': typeof apiApiCoffeeRoute
  '/api/presence': typeof apiApiPresenceRoute
  '/blog/$slug': typeof mainBlogSlugRoute
  '/newsletter/$slug': typeof mainNewsletterSlugRoute
  '/aoc': typeof mainAocIndexRoute
  '/blog': typeof mainBlogIndexRoute
  '/newsletter': typeof mainNewsletterIndexRoute
  '/foobar/$slug': typeof mainfoobarFoobarSlugRoute
  '/aoc/$year/$day': typeof mainAocYearDayRoute
  '/foobar': typeof mainfoobarFoobarIndexRoute
  '/prxy/plsbl/api/event': typeof apiPrxyPlsblApiEventRoute
  '/prxy/plsbl/js/$script': typeof apiPrxyPlsblJsScriptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/(pure)': typeof pureRouteRouteWithChildren
  '/(main)/$slug': typeof mainSlugRoute
  '/(main)/about': typeof mainAboutRoute
  '/(main)/karma': typeof mainKarmaRoute
  '/(main)/keebs': typeof mainKeebsRoute
  '/(main)/rwc': typeof mainRwcRoute
  '/(pure)/fancy-pants': typeof pureFancyPantsRoute
  '/(pure)/resume': typeof pureResumeRoute
  '/(main)/': typeof mainIndexRoute
  '/(api)/api/coffee': typeof apiApiCoffeeRoute
  '/(api)/api/presence': typeof apiApiPresenceRoute
  '/(main)/blog/$slug': typeof mainBlogSlugRoute
  '/(main)/newsletter/$slug': typeof mainNewsletterSlugRoute
  '/(main)/aoc/': typeof mainAocIndexRoute
  '/(main)/blog/': typeof mainBlogIndexRoute
  '/(main)/newsletter/': typeof mainNewsletterIndexRoute
  '/(main)/(foobar)/foobar/$slug': typeof mainfoobarFoobarSlugRoute
  '/(main)/aoc/$year/$day': typeof mainAocYearDayRoute
  '/(main)/(foobar)/foobar/': typeof mainfoobarFoobarIndexRoute
  '/(api)/prxy/plsbl/api/event': typeof apiPrxyPlsblApiEventRoute
  '/(api)/prxy/plsbl/js/$script': typeof apiPrxyPlsblJsScriptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$slug'
    | '/about'
    | '/karma'
    | '/keebs'
    | '/rwc'
    | '/fancy-pants'
    | '/resume'
    | '/'
    | '/api/coffee'
    | '/api/presence'
    | '/blog/$slug'
    | '/newsletter/$slug'
    | '/aoc/'
    | '/blog/'
    | '/newsletter/'
    | '/foobar/$slug'
    | '/aoc/$year/$day'
    | '/foobar/'
    | '/prxy/plsbl/api/event'
    | '/prxy/plsbl/js/$script'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$slug'
    | '/about'
    | '/karma'
    | '/keebs'
    | '/rwc'
    | '/fancy-pants'
    | '/resume'
    | '/'
    | '/api/coffee'
    | '/api/presence'
    | '/blog/$slug'
    | '/newsletter/$slug'
    | '/aoc'
    | '/blog'
    | '/newsletter'
    | '/foobar/$slug'
    | '/aoc/$year/$day'
    | '/foobar'
    | '/prxy/plsbl/api/event'
    | '/prxy/plsbl/js/$script'
  id:
    | '__root__'
    | '/(main)'
    | '/(pure)'
    | '/(main)/$slug'
    | '/(main)/about'
    | '/(main)/karma'
    | '/(main)/keebs'
    | '/(main)/rwc'
    | '/(pure)/fancy-pants'
    | '/(pure)/resume'
    | '/(main)/'
    | '/(api)/api/coffee'
    | '/(api)/api/presence'
    | '/(main)/blog/$slug'
    | '/(main)/newsletter/$slug'
    | '/(main)/aoc/'
    | '/(main)/blog/'
    | '/(main)/newsletter/'
    | '/(main)/(foobar)/foobar/$slug'
    | '/(main)/aoc/$year/$day'
    | '/(main)/(foobar)/foobar/'
    | '/(api)/prxy/plsbl/api/event'
    | '/(api)/prxy/plsbl/js/$script'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
  pureRouteRoute: typeof pureRouteRouteWithChildren
  apiApiCoffeeRoute: typeof apiApiCoffeeRoute
  apiApiPresenceRoute: typeof apiApiPresenceRoute
  apiPrxyPlsblApiEventRoute: typeof apiPrxyPlsblApiEventRoute
  apiPrxyPlsblJsScriptRoute: typeof apiPrxyPlsblJsScriptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(pure)': {
      id: '/(pure)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof pureRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(pure)/resume': {
      id: '/(pure)/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof pureResumeRouteImport
      parentRoute: typeof pureRouteRoute
    }
    '/(pure)/fancy-pants': {
      id: '/(pure)/fancy-pants'
      path: '/fancy-pants'
      fullPath: '/fancy-pants'
      preLoaderRoute: typeof pureFancyPantsRouteImport
      parentRoute: typeof pureRouteRoute
    }
    '/(main)/rwc': {
      id: '/(main)/rwc'
      path: '/rwc'
      fullPath: '/rwc'
      preLoaderRoute: typeof mainRwcRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/keebs': {
      id: '/(main)/keebs'
      path: '/keebs'
      fullPath: '/keebs'
      preLoaderRoute: typeof mainKeebsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/karma': {
      id: '/(main)/karma'
      path: '/karma'
      fullPath: '/karma'
      preLoaderRoute: typeof mainKarmaRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/about': {
      id: '/(main)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof mainAboutRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/$slug': {
      id: '/(main)/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof mainSlugRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/newsletter/': {
      id: '/(main)/newsletter/'
      path: '/newsletter'
      fullPath: '/newsletter/'
      preLoaderRoute: typeof mainNewsletterIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/blog/': {
      id: '/(main)/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof mainBlogIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/aoc/': {
      id: '/(main)/aoc/'
      path: '/aoc'
      fullPath: '/aoc/'
      preLoaderRoute: typeof mainAocIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/newsletter/$slug': {
      id: '/(main)/newsletter/$slug'
      path: '/newsletter/$slug'
      fullPath: '/newsletter/$slug'
      preLoaderRoute: typeof mainNewsletterSlugRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/blog/$slug': {
      id: '/(main)/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof mainBlogSlugRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(api)/api/presence': {
      id: '/(api)/api/presence'
      path: '/api/presence'
      fullPath: '/api/presence'
      preLoaderRoute: typeof apiApiPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(api)/api/coffee': {
      id: '/(api)/api/coffee'
      path: '/api/coffee'
      fullPath: '/api/coffee'
      preLoaderRoute: typeof apiApiCoffeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/(foobar)/foobar/': {
      id: '/(main)/(foobar)/foobar/'
      path: '/foobar'
      fullPath: '/foobar/'
      preLoaderRoute: typeof mainfoobarFoobarIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/aoc/$year/$day': {
      id: '/(main)/aoc/$year/$day'
      path: '/aoc/$year/$day'
      fullPath: '/aoc/$year/$day'
      preLoaderRoute: typeof mainAocYearDayRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/(foobar)/foobar/$slug': {
      id: '/(main)/(foobar)/foobar/$slug'
      path: '/foobar/$slug'
      fullPath: '/foobar/$slug'
      preLoaderRoute: typeof mainfoobarFoobarSlugRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(api)/prxy/plsbl/js/$script': {
      id: '/(api)/prxy/plsbl/js/$script'
      path: '/prxy/plsbl/js/$script'
      fullPath: '/prxy/plsbl/js/$script'
      preLoaderRoute: typeof apiPrxyPlsblJsScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(api)/prxy/plsbl/api/event': {
      id: '/(api)/prxy/plsbl/api/event'
      path: '/prxy/plsbl/api/event'
      fullPath: '/prxy/plsbl/api/event'
      preLoaderRoute: typeof apiPrxyPlsblApiEventRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface mainRouteRouteChildren {
  mainSlugRoute: typeof mainSlugRoute
  mainAboutRoute: typeof mainAboutRoute
  mainKarmaRoute: typeof mainKarmaRoute
  mainKeebsRoute: typeof mainKeebsRoute
  mainRwcRoute: typeof mainRwcRoute
  mainIndexRoute: typeof mainIndexRoute
  mainBlogSlugRoute: typeof mainBlogSlugRoute
  mainNewsletterSlugRoute: typeof mainNewsletterSlugRoute
  mainAocIndexRoute: typeof mainAocIndexRoute
  mainBlogIndexRoute: typeof mainBlogIndexRoute
  mainNewsletterIndexRoute: typeof mainNewsletterIndexRoute
  mainfoobarFoobarSlugRoute: typeof mainfoobarFoobarSlugRoute
  mainAocYearDayRoute: typeof mainAocYearDayRoute
  mainfoobarFoobarIndexRoute: typeof mainfoobarFoobarIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainSlugRoute: mainSlugRoute,
  mainAboutRoute: mainAboutRoute,
  mainKarmaRoute: mainKarmaRoute,
  mainKeebsRoute: mainKeebsRoute,
  mainRwcRoute: mainRwcRoute,
  mainIndexRoute: mainIndexRoute,
  mainBlogSlugRoute: mainBlogSlugRoute,
  mainNewsletterSlugRoute: mainNewsletterSlugRoute,
  mainAocIndexRoute: mainAocIndexRoute,
  mainBlogIndexRoute: mainBlogIndexRoute,
  mainNewsletterIndexRoute: mainNewsletterIndexRoute,
  mainfoobarFoobarSlugRoute: mainfoobarFoobarSlugRoute,
  mainAocYearDayRoute: mainAocYearDayRoute,
  mainfoobarFoobarIndexRoute: mainfoobarFoobarIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

interface pureRouteRouteChildren {
  pureFancyPantsRoute: typeof pureFancyPantsRoute
  pureResumeRoute: typeof pureResumeRoute
}

const pureRouteRouteChildren: pureRouteRouteChildren = {
  pureFancyPantsRoute: pureFancyPantsRoute,
  pureResumeRoute: pureResumeRoute,
}

const pureRouteRouteWithChildren = pureRouteRoute._addFileChildren(
  pureRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
  pureRouteRoute: pureRouteRouteWithChildren,
  apiApiCoffeeRoute: apiApiCoffeeRoute,
  apiApiPresenceRoute: apiApiPresenceRoute,
  apiPrxyPlsblApiEventRoute: apiPrxyPlsblApiEventRoute,
  apiPrxyPlsblJsScriptRoute: apiPrxyPlsblJsScriptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
