export const BUTTONDOWN_EMAIL_MOCK = {
	results: [
		{
			id: "fd7005d9-89b4-433d-aa85-1d30dee35738",
			included_tags: [],
			excluded_tags: [],
			publish_date: "2021-01-17T13:31:59.083Z",
			subject: "Mocked newsletter email 1",
			body: "Hello there!\n\nHappy 2021 :)\n\n## New post on the blog!\n\nI posted on my blog this past week — about my [2020 in review](https://sreetamdas.com/blog/year-in-review-2020). It was a weird year for us all, but I was able to accomplish quite a lot still.\n\n## Keyboards\n\nIn some personal news, I started using my mechanical keyboard a lot more thanks to having my remote work setup complete. I'm slowly getting faster at typing as well—I'm at about 72 WPM. Also, if you haven't already, check out [monkeytype](https://monkeytype.com)!\n\nHere's a couple things that caught my eye this past month:\n\n![GMK Awaken](https://i.redd.it/utduohf5g4761.jpg)\n[GMK Awaken](https://redd.it/kje11i): a new keycap set announced over at [geekhack](https://geekhack.org/index.php?topic=109486.0).\n\n![KBDfans D65 with RAMA Heavy Industry](https://i.redd.it/505kqostiob61.jpg)\n[KBDfans D65 with RAMA Heavy Industry](https://redd.it/kyhbez)\n\n\n\n## To read\n\n- [How Discord Implemented App-Wide Keyboard Navigation](https://blog.discord.com/how-discord-implemented-app-wide-keyboard-navigation-abf073fd71de) — I've been a huge fan of Discord, and especially of their engineering team. If you're interested, they have another post that I'd highly recommend: [How Discord achieves native iOS performance with React Native](https://blog.discord.com/how-discord-achieves-native-ios-performance-with-react-native-390c84dcd502)\n- [A curious caching bug](https://actualbudget.com/blog/cursed-caching-curious)\n- [Let's Bring Spacer GIFs Back!](https://www.joshwcomeau.com/react/modern-spacer-gif/)\n\nThat's all for now! Once again, happy new year to you! May this year be everything that you want it to be 💜",
			secondary_id: 1,
			email_type: "public",
			slug: "mocked-newsletter-email-1",
			external_url: "",
			status: "sent",
			metadata: {},
		},
		{
			id: "0864c47f-3f94-4dee-9003-c3a9a69f8f39",
			included_tags: [],
			excluded_tags: [],
			publish_date: "2021-04-06T09:30:00Z",
			subject: "Mocked newsletter email 2",
			body: "Hello there!\n\nI'm getting back to working on my [website](https://sreetamdas.com/)! I'll be adding a (proper) mobile layout and RSS feed to begin with, and I'll be writing about my experience with it. Stay tuned for that :)\n\n## Personal News\n\nI spoke at [React Day Bangalore](https://reactday.in/)! It was a lightning talk about building a greenscreen with React and HTML Elements. This was my first ever conference talk and I am really glad at how well received it was. You can check out the [VOD](https://www.youtube.com/watch?v=vBO9jwotDgs) and the [slides](https://react-greenscreen.netlify.app/), and even see it [live in action](https://sreetamdas.com/talks/greenscreen).\n\n## To read\n\n- [The styled-components Happy Path](https://www.joshwcomeau.com/css/styled-components/)\n- [Porting a 100% local app to the web](https://actualbudget.com/blog/porting-local-app-web)\n- [Why Discord is switching from Go to Rust](https://blog.discord.com/why-discord-is-switching-from-go-to-rust-a190bbca2b1f)\n- [Supabase Launch Week](https://supabase.io/blog/2021/03/25/launch-week)\n\n## Keyboards\n\nI got better at typing! This was one of my best tests so far, but I've been averaging about 80-90 WPM now so it's definitely a lot of progress. In case you'd like to give it a shot as well, check out [monkeytype](https://monkeytype.com/).\n\n![https://i.imgur.com/UuFSsIl.png](https://i.imgur.com/UuFSsIl.png)\n\nI also bought a couple of keycap sets! They're not going to be delivered anytime soon but they look absolutely beautiful:\n\n[GMK Striker 2](https://zambumon.com/striker/)\n\n![https://zambumon.files.wordpress.com/2021/02/zambumon-gmk_striker_2-gallery_15-lb.jpg?w=1060&h=&zoom=2](https://zambumon.files.wordpress.com/2021/02/zambumon-gmk_striker_2-gallery_15-lb.jpg?w=1060&h=&zoom=2)\n\n[GMK Norse](https://omnitype.com/products/gmk-norse-keycap-set?variant=39272295432361)\n\n![https://i.imgur.com/baF36d1.png](https://i.imgur.com/baF36d1.png)\n\nThat's all for now! Have a great week and [stay safe](https://www.covid19india.org/) :)",
			secondary_id: 2,
			email_type: "public",
			slug: "mocked-newsletter-email-2",
			external_url: "",
			status: "sent",
			metadata: {},
		},
	],
	next: null,
	previous: null,
	count: 2,
};

export const BUTTONDOWN_SUBSCRIBERS_MOCK = {
	results: [
		{
			id: "f15f2875-8f3f-4b37-8d10-5b4e40ffaa3a",
			email: "jane.doe@gmail.com",
			notes: "",
			metadata: {},
			tags: [],
			referrer_url: "https://buttondown.email",
			creation_date: "2022-12-19T12:11:41.905Z",
			secondary_id: 2,
			subscriber_type: "regular",
			source: "organic",
			utm_campaign: "",
			utm_medium: "",
			utm_source: "",
		},
		{
			id: "e6c40df6-91d4-471b-906a-2b37c6bc130e",
			email: "john.doe@gmail.com",
			notes: "",
			metadata: {},
			tags: [],
			referrer_url: "https://buttondown.email",
			creation_date: "2021-11-17T08:22:40.880Z",
			secondary_id: 1,
			subscriber_type: "regular",
			source: "organic",
			utm_campaign: "",
			utm_medium: "",
			utm_source: "",
		},
	],
	next: "https://api.buttondown.email/v1/subscribers?page=2&type=regular",
	previous: null,
	count: 2,
};
